// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0TkponAqN3zE2ElBkXF0vPSBpMqKRa0',
    appId: '1:376101930767:web:27dbad76e61167b506e07a',
    messagingSenderId: '376101930767',
    projectId: 'fitness-app-114e8',
    authDomain: 'fitness-app-114e8.firebaseapp.com',
    storageBucket: 'fitness-app-114e8.firebasestorage.app',
    measurementId: 'G-H3H3XZ3MXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GZtZrXqLL5GM3U3CsliSM4_0T1NEOwY',
    appId: '1:376101930767:android:3a02e0955fc1672906e07a',
    messagingSenderId: '376101930767',
    projectId: 'fitness-app-114e8',
    storageBucket: 'fitness-app-114e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyY6lkGG4kGmOJigx06aAFI7KkA9DAjc',
    appId: '1:376101930767:ios:351b2f2ec230f42e06e07a',
    messagingSenderId: '376101930767',
    projectId: 'fitness-app-114e8',
    storageBucket: 'fitness-app-114e8.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGyY6lkGG4kGmOJigx06aAFI7KkA9DAjc',
    appId: '1:376101930767:ios:351b2f2ec230f42e06e07a',
    messagingSenderId: '376101930767',
    projectId: 'fitness-app-114e8',
    storageBucket: 'fitness-app-114e8.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS0TkponAqN3zE2ElBkXF0vPSBpMqKRa0',
    appId: '1:376101930767:web:f159b0ebd90a405006e07a',
    messagingSenderId: '376101930767',
    projectId: 'fitness-app-114e8',
    authDomain: 'fitness-app-114e8.firebaseapp.com',
    storageBucket: 'fitness-app-114e8.firebasestorage.app',
    measurementId: 'G-QNR2WY56QB',
  );
}
